AllCops:
  Excludes:
    - config/unicorn.rb
    - db/**
    - bin/bundle
  Rails:
    Enabled: true
Style/Documentation:
  Exclude:
    - db/migrate/*
    - config/application.rb
Metrics/MethodLength:
  Exclude:
    - db/migrate/*
